project_id = "xrzquagmoyxjhkkapagw"

[functions.mongodb]
verify_jwt = false

[functions.orders]
verify_jwt = false

[functions.reviews]
verify_jwt = false

[functions.chatbot]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.whatsapp-notify]
verify_jwt = false
